acr_login_server: "acrcasopractico2cfidrobo.azurecr.io"
acr_username: "acrcasopractico2cfidrobo"
acr_password: "6yuqL8j4nuT2ObZ7hpMmurVzaF0gEM5R1Dpd195B5IHCSRGsf5R7JQQJ99CCACMsfrFEqg7NAAACAZCRtLfJ"
web_image: "web/nginx-secure"
web_tag: "casopractico2"
