acr_login_server: "acrcasopractico2cfidrobo.azurecr.io"
acr_username: "acrcasopractico2cfidrobo"
acr_password: "3d3I6sJ3WQmQtVAtbbAyP80MIMgRXq09xRrwG4YGiP6NOULVNjNJJQQJ99CCACMsfrFEqg7NAAACAZCRh7hO"

web_image: "web/nginx-secure"
web_tag: "casopractico2"

nginx_basic_auth_user: "admin"
nginx_basic_auth_password: "Secadmin123"